@Library('Shared') _
pipeline {
    agent { label 'Node' }

    parameters {
        string(
            name: 'FRONTEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Frontend Docker tag of the image built by the CI job'
        )

        string(
            name: 'BACKEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Backend Docker tag of the image built by the CI job'
        )

        choice(
            name: 'DEPLOY_ENV',
            choices: ['local', 'prod'],
            description: 'Deployment Environment'
        )
    }

    stages {

        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage("Validate Parameters") {
            steps {
                script {
                    if (
                        !params.FRONTEND_DOCKER_TAG?.trim() ||
                        !params.BACKEND_DOCKER_TAG?.trim()
                    ) {
                        error("Docker tags missing")
                    }
                }
            }
        }

        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout(
                        "https://github.com/Ahad0p/Wanderlust-Mega-Project.git",
                        "main"
                    )
                }
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                    echo "DEPLOY_ENV: ${params.DEPLOY_ENV}"
                }
            }
        }

        stage("Update: Kubernetes manifests") {

            when {
                expression {
                    params.DEPLOY_ENV == "prod"
                }
            }

            steps {
                script {

                    dir('kubernetes') {

                        sh """
                        sed -i \
                        -e 's|wanderlust-backend-beta:.*|wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}|g' \
                        backend.yaml

                        sed -i \
                        -e 's|wanderlust-frontend-beta:.*|wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}|g' \
                        frontend.yaml
                        """
                    }
                }
            }
        }

        stage("Git: Code update and push to GitHub") {

            when {
                expression {
                    params.DEPLOY_ENV == "prod"
                }
            }

            steps {

                script {

                    withCredentials([
                        gitUsernamePassword(
                            credentialsId: 'Github-cred',
                            gitToolName: 'Default'
                        )
                    ]) {

                        sh '''
                        git status

                        git add .

                        git diff --cached --quiet || \
                        git commit -m "Update k8s manifests"

                        git push origin main
                        '''
                    }
                }
            }
        }
    }

    post {

        success {

            script {

                emailext(
                    attachLog: true,
                    from: 'ahadkhan.ai306@gmail.com',

                    subject:
                    "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",

                    body: """
                    <html>
                    <body>

                    <div style="background-color:#FFA07A;padding:10px;">
                        <p><b>Project:</b> ${env.JOB_NAME}</p>
                    </div>

                    <div style="background-color:#90EE90;padding:10px;">
                        <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                    </div>

                    <div style="background-color:#87CEEB;padding:10px;">
                        <p><b>URL:</b> ${env.BUILD_URL}</p>
                    </div>

                    </body>
                    </html>
                    """,

                    to: 'ahadkhan.ai306@gmail.com',
                    mimeType: 'text/html'
                )
            }
        }

        failure {

            script {

                emailext(
                    attachLog: true,
                    from: 'ahadkhan.ai306@gmail.com',

                    subject:
                    "Wanderlust Application build failed - '${currentBuild.result}'",

                    body: """
                    <html>
                    <body>

                    <div style="background-color:#FFA07A;padding:10px;">
                        <p><b>Project:</b> ${env.JOB_NAME}</p>
                    </div>

                    <div style="background-color:#90EE90;padding:10px;">
                        <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                    </div>

                    </body>
                    </html>
                    """,

                    to: 'ahadkhan.ai306@gmail.com',
                    mimeType: 'text/html'
                )
            }
        }
    }
}
